Adds `void` return type to Meteor.Collection<T>()
On TypeScript 0.9.7.0 the missing `void` return type generates the error TS2084: Call signatures used in a 'new' expression must have a 'void' return type.